/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.sql.*;

/**
 *
 * @author Evan Henderson
 */
public class AddKelas extends javax.swing.JFrame {

    static Connection conn = null;
    static Statement st = null;
    static ResultSet rs = null;

    /**
     * Creates new form Input
     */
    public AddKelas() {
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pplbo_quiz2", "root", "");
            System.out.println("Connected to database");
            st = conn.createStatement();
        } catch (Exception e) {
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        id_kelas = new javax.swing.JTextField();
        nama_kelas = new javax.swing.JTextField();
        submitTambahKelas = new javax.swing.JButton();
        header1 = new javax.swing.JLabel();
        backTambahMahasiswa = new javax.swing.JButton();
        submitUpdateKelas = new javax.swing.JButton();
        submitDeleteKelas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("ID Kelas");

        jLabel7.setText("Nama Kelas");

        id_kelas.setText("NULL");
        id_kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_kelasActionPerformed(evt);
            }
        });

        submitTambahKelas.setText("Submit");
        submitTambahKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitTambahKelasActionPerformed(evt);
            }
        });

        header1.setText("Kelas");

        backTambahMahasiswa.setText("Back");
        backTambahMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backTambahMahasiswaActionPerformed(evt);
            }
        });

        submitUpdateKelas.setText("Update");
        submitUpdateKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitUpdateKelasActionPerformed(evt);
            }
        });

        submitDeleteKelas.setText("Delete");
        submitDeleteKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitDeleteKelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))
                            .addComponent(backTambahMahasiswa))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(id_kelas)
                                .addComponent(nama_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(submitDeleteKelas)
                                .addGap(18, 18, 18)
                                .addComponent(submitUpdateKelas)
                                .addGap(18, 18, 18)
                                .addComponent(submitTambahKelas)))
                        .addGap(54, 54, 54))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header1)
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(id_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(nama_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backTambahMahasiswa)
                    .addComponent(submitTambahKelas)
                    .addComponent(submitUpdateKelas)
                    .addComponent(submitDeleteKelas))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_kelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_kelasActionPerformed

    private void submitTambahKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitTambahKelasActionPerformed
        // TODO add your handling code here:
        try {
            st.executeUpdate(String.format("INSERT INTO kelas VALUES(null,'%s');", this.nama_kelas.getText()));
            System.out.println("Data kelas berhasil dibuat");
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_submitTambahKelasActionPerformed

    private void backTambahMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backTambahMahasiswaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backTambahMahasiswaActionPerformed

    private void submitUpdateKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitUpdateKelasActionPerformed
        // TODO add your handling code here:
        try {
            st.executeUpdate(String.format("UPDATE kelas SET nama_kelas = '%s' WHERE id_kelas = %d", this.nama_kelas.getText(), Integer.parseInt(this.id_kelas.getText())));
            System.out.println("Data kelas telah diubah");
        } catch (SQLException e) {
            System.out.println("Data kelas gagal diubah, pastikan mahasiswa di kelas tersebut kosong");
        }
    }//GEN-LAST:event_submitUpdateKelasActionPerformed

    private void submitDeleteKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitDeleteKelasActionPerformed
        // TODO add your handling code here:
        try {
            st.executeUpdate(String.format("DELETE FROM kelas WHERE id_kelas = %d", Integer.parseInt(this.id_kelas.getText())));
            System.out.println("Data kelas telah dihapus");
        } catch (SQLException e) {
            System.out.println("Data kelas gagal dihapus, pastikan mahasiswa di kelas tersebut kosong");
        }
    }//GEN-LAST:event_submitDeleteKelasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddKelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backTambahMahasiswa;
    private javax.swing.JLabel header1;
    private javax.swing.JTextField id_kelas;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nama_kelas;
    private javax.swing.JButton submitDeleteKelas;
    private javax.swing.JButton submitTambahKelas;
    private javax.swing.JButton submitUpdateKelas;
    // End of variables declaration//GEN-END:variables
}
