package main;

import java.sql.*;
import javax.swing.DefaultComboBoxModel;

public class AddNilai extends javax.swing.JFrame {

    static Connection conn = null;
    static Statement st = null;
    static ResultSet rs = null;
    static int id_matkul;
    static String nim, nama_mahasiswa, nama_matakuliah;

    /**
     * Creates new form Input
     */
    public AddNilai() {
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pplbo_quiz2", "root", "");
            System.out.println("Connected to database");
            st = conn.createStatement();
        } catch (SQLException e) {
            System.out.println(e);
        }
        initComponents();
        mahasiswa.setModel(new DefaultComboBoxModel<>(new String[]{
            "pilih"
        }));
        try {
            rs = st.executeQuery("SELECT nama FROM mahasiswa");
            while (rs.next()) {
                mahasiswa.addItem(rs.getString("nama"));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
        matkul.setModel(new DefaultComboBoxModel<>(new String[]{
            "pilih"
        }));
        try {
            rs = st.executeQuery("SELECT nama_matkul FROM matkul");
            while (rs.next()) {
                matkul.addItem(rs.getString("nama_matkul"));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        id_data_nilai = new javax.swing.JTextField();
        header1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tugas1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tugas2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tugas3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tugas4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tugas5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        quiz1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        quiz2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        uts = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        uas = new javax.swing.JTextField();
        backTambahMahasiswa = new javax.swing.JButton();
        submitDeleteNilai = new javax.swing.JButton();
        submitUpdateNilai = new javax.swing.JButton();
        submitTambahNilai = new javax.swing.JButton();
        mahasiswa = new javax.swing.JComboBox<>();
        matkul = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("ID Nilai");

        id_data_nilai.setText("NULL");
        id_data_nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_data_nilaiActionPerformed(evt);
            }
        });

        header1.setText("Nilai");

        jLabel8.setText("Mahasiswa");

        jLabel9.setText("Matakuliah");

        jLabel10.setText("Tugas 1");

        tugas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tugas1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Tugas 2");

        tugas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tugas2ActionPerformed(evt);
            }
        });

        jLabel12.setText("Tugas 3");

        tugas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tugas3ActionPerformed(evt);
            }
        });

        jLabel13.setText("Tugas 4");

        tugas4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tugas4ActionPerformed(evt);
            }
        });

        jLabel14.setText("Tugas 5");

        tugas5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tugas5ActionPerformed(evt);
            }
        });

        jLabel15.setText("Quiz 1");

        quiz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quiz1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Quiz 2");

        quiz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quiz2ActionPerformed(evt);
            }
        });

        jLabel17.setText("UTS");

        uts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utsActionPerformed(evt);
            }
        });

        jLabel18.setText("UAS");

        uas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uasActionPerformed(evt);
            }
        });

        backTambahMahasiswa.setText("Back");
        backTambahMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backTambahMahasiswaActionPerformed(evt);
            }
        });

        submitDeleteNilai.setText("Delete");
        submitDeleteNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitDeleteNilaiActionPerformed(evt);
            }
        });

        submitUpdateNilai.setText("Update");
        submitUpdateNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitUpdateNilaiActionPerformed(evt);
            }
        });

        submitTambahNilai.setText("Submit");
        submitTambahNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitTambahNilaiActionPerformed(evt);
            }
        });

        mahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mahasiswaActionPerformed(evt);
            }
        });

        matkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matkulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(id_data_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addGap(167, 167, 167)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mahasiswa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(matkul, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(backTambahMahasiswa)
                                .addGap(29, 29, 29)
                                .addComponent(submitDeleteNilai)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(submitUpdateNilai)
                                        .addGap(18, 18, 18)
                                        .addComponent(submitTambahNilai))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tugas4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tugas3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tugas2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tugas1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tugas5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(103, 103, 103)
                                .addComponent(uts, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(90, 90, 90)
                                .addComponent(quiz2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(90, 90, 90)
                                .addComponent(quiz1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(uas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_data_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(mahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(matkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tugas1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tugas2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tugas3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tugas4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quiz1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quiz2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uts, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tugas5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backTambahMahasiswa)
                    .addComponent(submitTambahNilai)
                    .addComponent(submitUpdateNilai)
                    .addComponent(submitDeleteNilai))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_data_nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_data_nilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_data_nilaiActionPerformed

    private void submitTambahNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitTambahNilaiActionPerformed
        // TODO add your handling code here:
        System.out.println("NIM:"  + nim);
        System.out.println("ID Matkul: " + id_matkul);
        String format = String.format("%d, %d, %d, %d, %d, %d, %d, %d, %d", Integer.parseInt(tugas1.getText()), Integer.parseInt(tugas2.getText()), Integer.parseInt(tugas3.getText()), Integer.parseInt(tugas4.getText()), Integer.parseInt(tugas5.getText()), Integer.parseInt(quiz1.getText()), Integer.parseInt(quiz2.getText()), Integer.parseInt(uts.getText()), Integer.parseInt(uas.getText()));
        try {
            st.executeUpdate(String.format("INSERT INTO nilai VALUES (NULL, '%s', %d, %s, NULL)", nim, id_matkul, format));
            System.out.println("Data nilai berhasil dibuat");
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_submitTambahNilaiActionPerformed

    private void backTambahMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backTambahMahasiswaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backTambahMahasiswaActionPerformed

    private void submitUpdateNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitUpdateNilaiActionPerformed
        // TODO add your handling code here:
        String format = String.format("tugas1 = %d,tugas2 = %d,tugas3 = %d,tugas4 = %d,tugas5 = %d,quiz1 = %d,quiz2 = %d,uts = %d,uas = %d", Integer.parseInt(tugas1.getText()), Integer.parseInt(tugas2.getText()), Integer.parseInt(tugas3.getText()), Integer.parseInt(tugas4.getText()), Integer.parseInt(tugas5.getText()), Integer.parseInt(quiz1.getText()), Integer.parseInt(quiz2.getText()), Integer.parseInt(uts.getText()), Integer.parseInt(uas.getText()));
        try {
            String finalization = String.format("UPDATE nilai SET %s , nim = %s, id_matkul = %d WHERE id_data_nilai = %d", format, nim, id_matkul, Integer.parseInt(id_data_nilai.getText()));
            System.out.println(finalization);
            st.executeUpdate(finalization);
            System.out.println("Data nilai berhasil dibuat");
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_submitUpdateNilaiActionPerformed

    private void submitDeleteNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitDeleteNilaiActionPerformed
        // TODO add your handling code here:
        try {
            st.executeUpdate(String.format("DELETE FROM nilai WHERE id_data_nilai = %d", Integer.parseInt(id_data_nilai.getText())));
            System.out.println("Data nilai telah dihapus");
        } catch (SQLException e) {
            System.out.println("Data nilai gagal dihapus, pastikan data masukkan telah benar");
        }
    }//GEN-LAST:event_submitDeleteNilaiActionPerformed

    private void tugas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tugas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tugas1ActionPerformed

    private void tugas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tugas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tugas2ActionPerformed

    private void tugas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tugas3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tugas3ActionPerformed

    private void tugas4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tugas4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tugas4ActionPerformed

    private void tugas5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tugas5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tugas5ActionPerformed

    private void quiz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quiz1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quiz1ActionPerformed

    private void quiz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quiz2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quiz2ActionPerformed

    private void utsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utsActionPerformed

    private void uasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uasActionPerformed

    private void mahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mahasiswaActionPerformed
        // TODO add your handling code here:
        nama_mahasiswa = mahasiswa.getSelectedItem().toString();
        System.out.println(nama_mahasiswa);
        try {
            rs = st.executeQuery("SELECT nim FROM mahasiswa WHERE nama = '" + nama_mahasiswa + "'");
            rs.next();
            nim = rs.getString("nim");
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_mahasiswaActionPerformed

    private void matkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matkulActionPerformed
        // TODO add your handling code here:
        nama_matakuliah = matkul.getSelectedItem().toString();
        System.out.println(nama_matakuliah);
        try {
            rs = st.executeQuery("SELECT id_matkul FROM matkul WHERE nama_matkul = '" + nama_matakuliah + "'");
            rs.next();
            id_matkul = rs.getInt("id_matkul");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_matkulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backTambahMahasiswa;
    private javax.swing.JLabel header1;
    private javax.swing.JTextField id_data_nilai;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> mahasiswa;
    private javax.swing.JComboBox<String> matkul;
    private javax.swing.JTextField quiz1;
    private javax.swing.JTextField quiz2;
    private javax.swing.JButton submitDeleteNilai;
    private javax.swing.JButton submitTambahNilai;
    private javax.swing.JButton submitUpdateNilai;
    private javax.swing.JTextField tugas1;
    private javax.swing.JTextField tugas2;
    private javax.swing.JTextField tugas3;
    private javax.swing.JTextField tugas4;
    private javax.swing.JTextField tugas5;
    private javax.swing.JTextField uas;
    private javax.swing.JTextField uts;
    // End of variables declaration//GEN-END:variables
}
